name: Clown mode on April 1st

on:
  schedule:
    - cron: '0 0 1 4 *'

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run script
        run: echo "This is clown mode released 1st of  April each year, a souvenir of @MariuszRozycki."
